### ISSUE TITLE
View not working after bump to 1.1.5

### ISSUE THREAD

**Issue by Aragur** [patmood/pocketbase-typegen#52]
I'm using the view feature from pocketbase.
I'm using the `created` field, but typegen doesn't generate this. (`Property 'created' does not exist on type 'LastChatMessageResponse'.`)
That's my View SQL:

```
SELECT
  chats.id,
  chats.sender,
  chats.recipient,
  chats.message,
  MAX(chats.created) created
FROM chats
GROUP BY chats.sender, chats.recipient
ORDER BY created DESC
```

**Comment by patmood** [comment]
Thanks for reporting. I haven't used this feature much yet. Can you post:
- the the schema for your view (eg like [this](https://github.com/patmood/pocketbase-typegen/blob/main/test/pb_schema.json#L402) section in the test schema)
- an example item returned from the pocketbase API

If `created` is part of the schema, it should be part of the type. I'm also interested if it's not in the schema, but is in the API response.

**Comment by Aragur** [comment]
Sure, here is the schema:
```json
[
  {
    "id": "fieq778roj57g1f",
    "name": "chats",
    "type": "base",
    "system": false,
    "schema": [
      {
        "id": "mxcpyfox",
        "name": "sender",
        "type": "relation",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "collectionId": "_pb_users_auth_",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": []
        }
      },
      {
        "id": "wxxgchig",
        "name": "recipient",
        "type": "relation",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "collectionId": "_pb_users_auth_",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": []
        }
      },
      {
        "id": "y7rs870z",
        "name": "message",
        "type": "text",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      },
      {
        "id": "fywdiyif",
        "name": "read",
        "type": "bool",
        "system": false,
        "required": false,
        "unique": false,
        "options": {}
      }
    ],
    "listRule": "@request.auth.id = sender.id || @request.auth.id = recipient.id",
    "viewRule": null,
    "createRule": "@request.auth.id != \"\" && @request.auth.id = @request.data.sender.id",
    "updateRule": "@request.auth.id = sender.id || @request.auth.id = recipient.id",
    "deleteRule": null,
    "options": {}
  },
  {
    "id": "ro65wim3sk4x72m",
    "name": "lastChatMessage",
    "type": "view",
    "system": false,
    "schema": [
      {
        "id": "mxcpyfox",
        "name": "sender",
        "type": "relation",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "collectionId": "_pb_users_auth_",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": []
        }
      },
      {
        "id": "wxxgchig",
        "name": "recipient",
        "type": "relation",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "collectionId": "_pb_users_auth_",
          "cascadeDelete": false,
          "minSelect": null,
          "maxSelect": 1,
          "displayFields": []
        }
      },
      {
        "id": "y7rs870z",
        "name": "message",
        "type": "text",
        "system": false,
        "required": true,
        "unique": false,
        "options": {
          "min": null,
          "max": null,
          "pattern": ""
        }
      }
    ],
    "listRule": "",
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "options": {
      "query": "SELECT\n  chats.id,\n  chats.sender,\n  chats.recipient,\n  chats.message,\n  MAX(chats.created) created\nFROM chats\nGROUP BY chats.sender, chats.recipient\nORDER BY created DESC"
    }
  }
]
```

And here is an example item returned by the API:
```json
{
  "collectionId": "ro65wim3sk4x72m",
  "collectionName": "lastChatMessage",
  "created": "2023-02-27 13:28:27.439Z",
  "id": "12k1tbdihnmxhae",
  "message": "Test",
  "recipient": "ubzfyma8qx2793t",
  "sender": "gem97qgk5fc1vn1",
  "updated": "",
  "expand": {}
}
```

**Comment by patmood** [comment]
I see. I removed `created`/`updated` from the base type since they're not populated automatically for views. Looks like if you do include it via SQL, the system fields are used. I'll add it back 👍

**Comment by Aragur** [comment]
Yes, looks like so. If you use `created` or `updated` pocketbase doesn't add this to the schmea.
Thanks a lot :)

**Comment by patmood** [comment]
I just released 1.1.7. Give it a shot and let me know if there's any other issues

**Comment by Aragur** [comment]
@patmood The issue was fixed perfectly. Thanks a lot :)
